### ISSUE TITLE
Timeout error when setting a parameter

### ISSUE THREAD

**Issue by eminakgun** [dronekit/dronekit-python#1011]
Hi,
I am trying to set some of the takeoff mode parameters for ArduPlane, but dronekit outputs timeout errors.
```
vehicle.parameters['TKOFF_ALT '] = 100
vehicle.parameters['TKOFF_DIST '] = 50
```

> ERROR:dronekit:timeout setting parameter TKOFF_DIST  to 50.000000
> ERROR:dronekit:timeout setting parameter TKOFF_ALT  to 100.000000

But,
```
vehicle.parameters['TKOFF_THR_MAX'] = 100
vehicle.parameters['TKOFF_LVL_PITCH'] = 15
```
works fine.
What might be the problem?

**Comment by mustafa-gokce** [comment]
```
vehicle.parameters['TKOFF_ALT '] = 100
vehicle.parameters['TKOFF_DIST '] = 50
```
Why there are whitespaces after the parameter names?
