### ISSUE TITLE
battery value is empty

### ISSUE THREAD

**Issue by HannHank** [dronekit/dronekit-python#1028]
I recently build a drone and after everything worked in APM Mission Planner I started to experimenting with DroneKit. But for some reason the **battery value** of my vehicle is **empty** although it works in APM Mission Planner.  Do I habe to set the Flightcontroller type, and the Powermodule-Type of the Flightcontroller I am using? (I had to do this in Mission Planner to get it to work properly)

### Hardware:
- Pixhwak
- Pixhawk Power-module

**Comment by bduva002** [comment]
What are you using to read battery value ie vehicle.??????

**Comment by HannHank** [comment]
I had a small issue in my code base, fixed it and everything worked great.
