### ISSUE TITLE
RC controller mode changes not taking when connected to onboard computer

### ISSUE THREAD

**Issue by lachlanbrewster1** [dronekit/dronekit-python#1081]
I am currently finding that my drone tends to ignore the mode changes sent to it from my radio control when in flight while my onboard computer is connected (via serial - telem2).

This happens both when I am sending commands via the onboard computer / dronekit, and when I am definitely not sending any commands. And no, I am definitely not repeatedly sending mode change requests in my code.

Eventually (after spamming the button) it will change mode, but this is slightly worrying. Has anyone else experienced this?

Thanks

**Comment by lachlanbrewster1** [comment]
For anyone in the future coming across this;
I was using a herelink controller, which apparently also uses dronekit/pymavlink/something to talk to the flight controller in some instances. This means that it connects using the same system source as what my code tries to use (the default is 255), so my connection and the herelink connection were arguing/fighting with eachother over who gets to talk to the flight controller. Changed source_system=1 when I connect and it worked out.

**Comment by kpguru20001** [comment]
@lachlanbrewster1 can u share the piece of code u used to connect dronekit and herelink

**Comment by munsterlander** [comment]
Please with the code. Herelink is causing me fits.
