### ISSUE TITLE
Application for Maintaining the DroneKit-Python Project

### ISSUE THREAD

**Issue by divsa** [dronekit/dronekit-python#1191]
Hello,

I hope this message finds you well. I am writing to express my interest in maintaining the DroneKit-Python project. I have been a professional Python developer for several years, and while exploring solutions to use during my current employment, I discovered DroneKit. I've found it to be an immensely useful tool and I am keen on helping to ensure its continued success and utility. In fact, my very intention today was to fork the project to update it for my personal use. The synchronicity of your post seeking a maintainer on the very same day feels remarkably fortuitous.

Although I am relatively new to the domain of MAVLink and UAV technologies, I find it extremely exciting and I am willing to devote my time to understanding the current status of the project, the existing issues, and the potential areas for enhancement. Given my Python experience, I am confident that I can help to maintain the project's quality and even bring it up to date. 

My immediate plan would be to transition over to Python 3 and ensure that the project runs out of the box to minimize friction for new developers. Next, I would start by tackling the CI and PR backlog, and subsequently focus on addressing any other key issues and improving the functionality based on the community's feedback.

Best,
Div

**Comment by hamishwillee** [comment]
@divsa Apologies, I did not see this post until after you you close it. If you are still interested in contributing, you would be welcome. @morzack is going to be doing some of the same work as you were interested in, and having two people working on this would likely be better, in particular with respect to review. 

You might, for example, start by looking at the older PRs and commenting as to whether you think they make sense, and why.

**Comment by divsa** [comment]
Thanks, I just saw this. I will start looking at PR's and reach out to @morzack next week

**Comment by hamishwillee** [comment]
I think he's busy until the week after, but thank you.

**Comment by morzack** [comment]
@divsa Feel free to reach out any time about coordination -- my email is in my bio
