### ISSUE TITLE
motor keep getting disarmed and it cannot perform the simple_goto.py script

### ISSUE THREAD

**Issue by SHIVAPK80** [dronekit/dronekit-python#1194]
Got COMMAND_ACK: NAV_TAKEOFF: FAILED
Got COMMAND_ACK: REQUEST_MESSAGE: UNSUPPORTED
Got COMMAND_ACK: REQUEST_MESSAGE: UNSUPPORTED
Got COMMAND_ACK: REQUEST_AUTOPILOT_CAPABILITIES: FAILED
Got COMMAND_ACK: DO_SEND_BANNER: UNSUPPORTED
Got COMMAND_ACK: DO_SEND_BANNER: UNSUPPORTED
AP: Frame: QUAD

**Comment by hamishwillee** [comment]
I suggest you add information about what autopilot you are connecting to and version, also a link to the exact script you are running.

The fact that you are getting these ACKS tells me that whatever message you are specifying is not supported for requesting.

**Comment by SHIVAPK80** [comment]
thanks man it got resolved.........
