### ISSUE TITLE
I want to commit to this project

### ISSUE THREAD

**Issue by sahilbalia** [dronekit/dronekit-python#1206]
I am interested to work in domain of inter drone communication software and I want to contribute to this project.

**Comment by hamishwillee** [comment]
Hi @sahilbalia 

That would be great. @morzack Any suggestions on the best way to onboard @sahilbalia ?

**Comment by hamishwillee** [comment]
So you're saying you want to help from others to create simulations. In that case the best place to ask is probably the gitter channel.
