### ISSUE TITLE
What drone can I use this with?

### ISSUE THREAD

**Issue by Regenhardt** [dronekit/dronekit-python#1232]
Got an idea 16p drone and don't even know how to start. It's completely optional but would be nice to be able to program it.

**Comment by hamishwillee** [comment]
A drone that has an onboard computer that can run Python, and a flight controller that can run ArduPilot flight stack (by preference, with this particular library).

**Comment by Regenhardt** [comment]
Ok I see, nothing like that available on my drone, thanks!
