### ISSUE TITLE
fails to find "../src/google/protobuf/unittest.proto" during pip install

### ISSUE THREAD

**Issue by codywburns** [dronekit/dronekit-python#125]
During installation on Intel Edison,  it is failing during the pip install phase because it is not finding "../src/google/protobuf/unittest.proto" 

This causes a 'Failed to load module: No module named google.protobuf.internal' error when trying to load the droneapi module in mavproxy.

The error is caused by ['protobuf >= 2.5.0' ],which pulls the pip protobuf and still has line 73 as:
 
    def GenerateUnittestProtos():
      generate_proto("../src/google/protobuf/unittest.proto")

The official git has updated setup.py to include:
    
    def GenerateUnittestProtos():
        # Unittest protos are only needed for development.
        if not os.path.exists("../.git"):
        return
    generate_proto("../src/google/protobuf/unittest.proto")

This problem can be fixed by editing the protobuf/setup.py file and re-running pip install.

**Comment by tcr3dr** [comment]
This will no longer be an issue since https://github.com/dronekit/dronekit-python/pull/341 .
