### ISSUE TITLE
Vehicle.location reports incorrect is_relative value for Copter

### ISSUE THREAD

**Issue by hamishwillee** [dronekit/dronekit-python#130]
If you print out the location (on SITL) then you get:

* Copter: Location:lat=-35.3632507,lon=149.1652309,alt=0.0,is_relative=False
* Plane: Location:lat=-35.3632507,lon=149.1652309,alt=584.309997559,is_relative=False

The copter is_relative setting value is clearly wrong, since we're not at sea level.

**Comment by tcr3dr** [comment]
Merging with #306.
