### ISSUE TITLE
Web tests are only run on branches, not forks.

### ISSUE THREAD

**Issue by tcr3dr** [dronekit/dronekit-python#215]
Need a workflow that routes around this issue.

**Comment by tcr3dr** [comment]
One solution is to not try the web-based tests on nonlocal forks, which is probably the most straightforward solution.

**Comment by hamishwillee** [comment]
@tcr3dr What do the web tests cover that would be missed out? ie If we have tests then presumably they are important to run?

**Comment by tcr3dr** [comment]
@hamishwillee I realize that tests are actually being run on Circle CI and Appveyor, and only Travis is excluded. So disabling web tests only for Travis still gives us full coverage.

What is actually of concern is that we have an API key that we expose in our tests. Unsure what to do about that other than to be vigilant.

**Comment by hamishwillee** [comment]
@tcr3dr Good news.

> What is actually of concern is that we have an API key that we expose in our tests. Unsure what to do about that other than to be vigilant.

Bearing in mind that I know nothing about our infrastructure, some ideas

* Only allow requests from that key from certain IP addresses
* Run tests on mirrored test database, and ensure that key only has access to that database

**Comment by tcr3dr** [comment]
This is mostly a PR hygeine issue. I don't think there is a solution except for running these tests locally, for now.
