### ISSUE TITLE
Rename "droneapi" instances

### ISSUE THREAD

**Issue by tcr3dr** [dronekit/dronekit-python#219]
Maintaining a list of things here.

- [ ] top-level module is "droneapi"
- [ ] README.md - #241 

etc.

**Comment by tcr3dr** [comment]
Also see https://github.com/dronekit/dronekit-python/issues/241

**Comment by mrpollo** [comment]
updated your original issue to add the #241 issue :)

**Comment by squilter** [comment]
fixed with 4e20771bffddbc2c852bebcd43bec8e8e28026c1

**Comment by tcr3dr** [comment]
Boom.
