### ISSUE TITLE
Expose home location as separate from .commands array

### ISSUE THREAD

**Issue by tcr3dr** [dronekit/dronekit-python#252]
#230 #207 #132 

Home location doesn't act in the same way as our .commands array (see above topic for discussion). Instead of patching unexpected behavior, we can extract this "initial" command as a separate `Vehicle.home_location` variable.

**Comment by hamishwillee** [comment]
The attribute should also be settable (the [MAV_CMD_DO_SET_HOME](http://copter.ardupilot.com/wiki/common-planning-a-mission-with-waypoints-and-events/common-mavlink-mission-command-messages-mav_cmd/#mav_cmd_do_set_home) command can be set any time)

FYI, the ardupilot implementation of home location as first waypoint is a "bug" that they hope to undo at some point.

**Comment by hamishwillee** [comment]
This is fixed by #384

**Comment by tcr3dr** [comment]
Complete!
