### ISSUE TITLE
Add loading of dronekit module to mavinit.scr in dronekit installer

### ISSUE THREAD

**Issue by hamishwillee** [dronekit/dronekit-python#267]
It would remove one step for users if the dronekit installer automatically set up dronekit api to be loaded into mavproxy. This is particularly important because the mavinit.scr is cleared whenever you reinstall mavproxy.

The required line is (I believe):

```
echo module load droneapi.module.api >> %HOMEPATH%\AppData\Local\MAVProxy\mavinit.scr
```

Ideally run this conditional on it not being present already :-)

@stephendade @tcr3dr  Thoughts?

**Comment by stephendade** [comment]
@hamishwillee - done in #271 :)

**Comment by hamishwillee** [comment]
@stephendade Thank you! I'll update the docs in line with this today (hopefully!)

**Comment by tcr3dr** [comment]
We will no longer need this since DKPY2.
