### ISSUE TITLE
DKPY2: Cannot connect outside of mavproxy

### ISSUE THREAD

**Issue by ssoRL** [dronekit/dronekit-python#309]
Hi, I'd be very interested having <a href="https://github.com/dronekit/dronekit-python/issues/299">this</a> for the project that I'm working on, and decided to see if I could get it working on my system (Ubuntu 14.04). However when I try to connect to sitl, by running "droneapi.connect("127.0.0.1:4444")" on the python command prompt, the command prints "Started.", but then never returns (this seems to be happening somewhere in the MPFakeState prepare function). Any idea what would cause this?
currently on tcr-nomp branch
sitl started with sim_vehicle.sh --map --out=127.0.0.1:4444
#299 
@jlian

**Comment by hamishwillee** [comment]
@tcr3dr I'm not even getting this far - when I try and import "connect" I get `ImportError: No module named numpy`

**Comment by jlian** [comment]
That's weird, numpy should come preinstalled,

**Comment by hamishwillee** [comment]
> That's weird, numpy should come preinstalled,

Not pre-installed on Windows, though of course that might depend on the distribution.

It is weird though, because I don't get the error when connecting from a script.

**Comment by hamishwillee** [comment]
I'm closing this. The issue was fixed, and numpy is no longer a dependency.
