### ISSUE TITLE
wrong URL in docs

### ISSUE THREAD

**Issue by jason4short** [dronekit/dronekit-python#322]
Instructions have wrong URL:

git clone http://github.com/dronekit/droneapi-python.git

should be:
git clone http://github.com/dronekit/dronekit-python.git

**Comment by hamishwillee** [comment]
@jason4short - Thanks for that. I've patched this in #320 which means that it will go live (assuming it is integrated) when DKPY2.0 is released. Not sure entirely when that will be.
