### ISSUE TITLE
Mode not changed when message sent inside drone delivery example

### ISSUE THREAD

**Issue by hamishwillee** [dronekit/dronekit-python#357]
@tcr3dr 

I can't get the drone_delivery example to work. I've [updated it in this gist](https://gist.github.com/hamishwillee/22102fe31c3473c3a36e). Unfortunately it won't take off because the command to change the mode to guided never succeeds - it just sits there in the wrong mode. 

The same code run in a "normal" environment does work - you can test this by just enabling [this line](https://gist.github.com/hamishwillee/22102fe31c3473c3a36e#file-drone_delivery-py-L82).

I have also seen cases while experimenting where I changed the mode manually in the simulator via mavproxy, and this change was not detected - though the system sat there telling me it was getting the wrong mode.

I've tried lots of "trial and error" but I can't work out why it works in one case and not the other. Needs debugging from someone who can check the messages are actually being sent.

**Comment by tcr3dr** [comment]
Addressed by #361.
