### ISSUE TITLE
Cannot upload waypoints

### ISSUE THREAD

**Issue by hamishwillee** [dronekit/dronekit-python#376]
In dronekit 2.0.0c1 running on windows the examples mission_basic.py and mission_import_export.py demonstrate that command uploading is not working. Clearing waypoints works, downloading waypoints works, going into auto mode for an existing set of waypoints works, but uploading new waypoints does not. 

In mission_basic.py this was checked by running the example while watching in MP, and adding a line to look at the current mode. The example clears existing waypoints and then attempts to upload new ones. The waypoints are visibly cleared, but the new ones are not uploade/visible in mission planner. As a result the example get stuck when "starting the mission" because the autopilot will not allow you to change to auto mode if there are no waypoints.

mission_import_export.py similarly shows that after uploading the new set of waypoints, if you download them again you get nothing back.

I tried this on two versions of SITL and verified that waypoints can be written using MP. This code worked in dk1.5.

**Comment by tcr3dr** [comment]
This was fixed by #381.
