### ISSUE TITLE
Vehicle.commands.next is not writeable

### ISSUE THREAD

**Issue by hamishwillee** [dronekit/dronekit-python#390]
In DKPY1.0 the next field on commands was writeable to skip a step in a command sequence. This does not appear to be the case in #384 - you can change the value but any change is ignored. The mission_basic.py in that pull request demonstrates this (ie the [skip here is ignored]().

**Comment by hamishwillee** [comment]
I don't know what last_waypoint is, but this has changed the meaning of next!

Previously next meant "the waypoint you are heading towards". So initially this returns 0, but as soon as you start moving it reports next as "1" the first waypoint. When you reach the waypoint the system reports "Reached waypoint 1". In the current branch now it is reporting "next" as the waypoint you just went to - the last waypoint. This means that you get next reported as 0 when you're heading towards the first waypoint. 

In addition, the mission_basic.py example shows that vehicle.commands.next is still not settable - ie in dkpy 1.0 as soon as you changed the number this was written and the target changed ... now changing the value makes no difference at all

**Comment by hamishwillee** [comment]
This is not fixed (rc7/today's master). The .next command is ignored - the test code is the example mission_export.py in the master codeline.

There is an associated issue #419 which also breaks this example.

**Comment by tcr3dr** [comment]
Fixed by #423 (on rc8).
