### ISSUE TITLE
DKPY2:  autopilot baudrate locked to 115200, should be configurable

### ISSUE THREAD

**Issue by a7scenario** [dronekit/dronekit-python#393]
In DroneKit Python ver. 2 (DKPY2), the connect() function uses mavutil's mavlink_connection function to open a serial connection to the autopilot.  The issue is that connect's call to mavlink_connection doesn't specify a baudrate and, therefore, mavlink_connection just uses its default baudrate of 115200.  If I'm not mistaken, this means there is no way to change the baudrate of the connection between a Companion Computer and an autopilot if you're using DKPY2.  It would be better if connect() added an input argument of baudrate=115200 that it relays to mavlink_connection, to allow for using different baudrates with your autopilot. 

    def connect(ip , await_params=False, status_printer=errprinter, vehicle_class=Vehicle, rate=4):
        state = MPFakeState(mavutil.mavlink_connection(ip), vehicle_class=vehicle_class)
        state.status_printer = status_printer
        state.prepare(await_params=await_params, rate=rate)
        return state.vehicle

**Comment by tcr3dr** [comment]
Hi @a7scenario,

I'll add this ASAP to `connect()`. Thanks for filing this issue.

**Comment by tcr3dr** [comment]
We'll publish this in the next rc, coming shortly.

**Comment by hamishwillee** [comment]
I thought you could just pass the baudrate to the string  ``connect('com14 --baudrate 15000')``. This will require docs - and a fix to the connection string options http://python.dronekit.io/guide/getting_started.html#connecting-to-a-vehicle
