### ISSUE TITLE
Vehicle.commands.next returns last waypoint not next waypoint

### ISSUE THREAD

**Issue by hamishwillee** [dronekit/dronekit-python#419]
The reported vehicle.commands.next value is numerically the waypoint that was just left rather than the waypoint that you're heading towards. This is incorrect

You can see the behaviour by observing mission_basic.py example (note we're reporting next waypoint as 0 (incorrect), then the system reports we've reached waypoint 1 (correctly)
```
Distance to waypoint (0): None
Distance to waypoint (0): None
Distance to waypoint (0): None
>>> Reached Command #1
Distance to waypoint (1): 7.44343078803
Distance to waypoint (1): 3.82302758257
```
As an aside, this causes the example to misreport the distance to the next waypoint (and rather report the distance from the last waypoint)

**Comment by tcr3dr** [comment]
Fixed by #423.
