### ISSUE TITLE
Typo in init_py for global frame initialiser

### ISSUE THREAD

**Issue by hamishwillee** [dronekit/dronekit-python#453]
In definition of ``class LocationGlobal(object):``
see
```
       self.global_fame = None
```

**Comment by tcr3dr** [comment]
Oy.

**Comment by hamishwillee** [comment]
@tcr3dr I know you want global fame, but you just can't achieve it.

**Comment by tcr3dr** [comment]
@hamishwillee Maybe if I commit to it!

**Comment by hamishwillee** [comment]
No like button here, but i do :-)

**Comment by tcr3dr** [comment]
Going to be fixed by #445.
