### ISSUE TITLE
Differences between vehicle.commands.goto and vehicle.simple_goto (GUIDED mode)

### ISSUE THREAD

**Issue by sahiljuneja** [dronekit/dronekit-python#510]
Hello,

I believe in the most recent "major update" for DKP2.0, there were changes made to the goto and takeoff commands. I have tested out DKP1.0 and then DKP2.0 before this update. 

If I set a GPS location for the drone to go to, followed by another GPS location after reaching the first one, all I had to do was define the command with the GPS coordinates, and then queue up the next command. And it would fly to the first point, and then to the next one. I didn't have to add any checks to ensure that the drone had indeed reached the first GPS position before executing the next command. I thought there was an internal check in your of Pixhawk's code. 

Now I am testing the latest DPK2.0 release with the changes to the commands - vehicle.simple_goto.
I repeat the above process, but this time, the next command is getting executed immediately. Which causes erratic behaviour

There's no apparent change in my code. So I wonder what the difference is between the two. If there isn't, then this behaviour is bit odd since the difference lies within me shifting to DKP2.0 only. (I will try to backtrack my code as well in the mean time just to be sure.)

**Comment by hamishwillee** [comment]
@sahiljuneja There is no difference between the two in this respect.  Both DKPY1.0 and DKPY2.0  simply send ALL commands immediately, and these are executed immediately by the autopilot. If the second command arrives before the first has a chance to complete the first command is lost. So in both versions if you don't want the second command to be immediately implemented you need to put in either wait time or use some other way to ensure that the first command has a chance to complete (e.g. GPS).

I don't know why you were seeing other behaviour, but I am quite certain that this is how it was in both versions. I am therefore closing.
