### ISSUE TITLE
Vehicle.battery returns 0.0 voltage and "None" current repeatedly

### ISSUE THREAD

**Issue by sahiljuneja** [dronekit/dronekit-python#512]
Hello,

I am trying to utilize vehicle.battery command to obtain the battery status from my drone. However even over a period of time I get zero voltage.  

Is there any particular reason for this to happen?

**Comment by sahiljuneja** [comment]
Didn't know I have to enable Battery Monitoring via Mission Planner for this to work.

**Comment by hamishwillee** [comment]
@sahiljuneja Exactly what did you need to do? DroneKit simply converts the battery status messages it receives from the vehicle into an attribute - so provided the messages are sent you will get values.

**Comment by sahiljuneja** [comment]
@hamishwillee That's exactly what I was trying to do. But as I mentioned above, I had to enable "Battery Monitoring" option from the Mission Planner so that the drone can actually send back battery information.  It's working properly after I enabled that.
