### ISSUE TITLE
Channel Override needed? for forth and back Movement

### ISSUE THREAD

**Issue by Password2501** [dronekit/dronekit-python#567]
Hi, 
Me and a Friend are working intensively on a Copter that is keeping it's distance from a wall,
As a distance measurement we do have a laser and a python-code that measures accurately. So our only option is to implement it with the channel override function.

Do you guys know a better way?
forth and back commands without using the GPS-coordinates

Thanks in Advance

**Comment by hamishwillee** [comment]
I would at least try driving it using velocity commands as per http://python.dronekit.io/guide/copter/guided_mode.html#velocity-control

A better place to discuss this would be the ardupilot forums - because the best mechanism to use is defined in the autopilot and not dronekit.

Closing this here.

**Comment by Password2501** [comment]
This wasn't very helpful...

**Comment by hamishwillee** [comment]
I'm sorry it wasn't helpful. I don't know the answer; I've pointed you to the people who will be able to tell you whether velocity control is a reasonable option.
