### ISSUE TITLE
Add copyright to all the example source files

### ISSUE THREAD

**Issue by hamishwillee** [dronekit/dronekit-python#568]
As discussed in https://github.com/PX4/Firmware/pull/3790#issuecomment-185616039

**Comment by brenton311** [comment]
Should the copyright notice be added to main source code along with the example source files?

**Comment by hamishwillee** [comment]
Possibly. Not urgent though.

**Comment by brenton311** [comment]
Added copyright notice to example files: https://github.com/dronekit/dronekit-python/pull/631
