### ISSUE TITLE
appveyor environment is causing timeout issues

### ISSUE THREAD

**Issue by mrpollo** [dronekit/dronekit-python#574]
https://ci.appveyor.com/project/3drobotics/dronekit-python/build/1.0.352

**Comment by tcr3dr** [comment]
This is probably super specific to the MAVLink forwarding feature we have. I imagine all other tests are passing on Windows. A developer with Windows would be able to debug that MAVLink test fairly straightforwardly.

**Comment by mrpollo** [comment]
I disabled the Appveyor CI until we figure out how to fix it

**Comment by pietrodn** [comment]
AppVeyor [works](https://ci.appveyor.com/project/pietrodn/dronekit-python/builds/20386105) on the latest master and can be re-enabled. See #878.

**Comment by pietrodn** [comment]
AppVeyor builds are now enabled, running and successful. This issue can be closed. 🥳

**Comment by peterbarker** [comment]
Closed, thanks!
