### ISSUE TITLE
New DK release

### ISSUE THREAD

**Issue by LorenzMeier** [dronekit/dronekit-python#588]
@sanderux Proposed a few PRs which are critical for our use of Dronekit. Would it be possible to get a new Python release so we don't have to point people at building from source?

/cc @mrpollo

**Comment by mrpollo** [comment]
We'll have a new release soon, we are just waiting on a few PR's to get merged, won't take long

**Comment by mrpollo** [comment]
2.3.0 is out!, we also published to pypi https://pypi.python.org/pypi/dronekit

**Comment by hamishwillee** [comment]
FYI, I also updated the release notes in the docs with https://github.com/dronekit/dronekit-python/pull/590 and the notes on the DK discuss forum.
