### ISSUE TITLE
Nudging copter's position using visual cues

### ISSUE THREAD

**Issue by DarylWM** [dronekit/dronekit-python#599]
I'd like to tweak the Solo's position as it descends onto a mat, using cues from the camera. In GUIDED mode I thought I could get it in the proximity of the mat using GPS, and then slowly descend at 0.5 m/s, applying a little bit of roll / pitch / yaw as it goes to keep the mat in the centre of the image, and then land it.

I know using channel overrides is discouraged, but is there a better way to do it?

When I try to use overrides in SITL though, the overrides seem to be ignored, as in this cut-down example.

```
arm_and_takeoff(10)

print("Simulating user input...")
vehicle.channels.overrides['1'] = 1100
vehicle.channels.overrides['2'] = 1100
time.sleep(10)
vehicle.channels.overrides['1'] = None
vehicle.channels.overrides['2'] = None

print("Setting LAND mode...")
vehicle.mode = VehicleMode("LAND")

```

**Comment by hamishwillee** [comment]
Yes. 3DR have hidden access to the channel overrides. Some things are available in https://github.com/dronekit/dronekit-python-solo but not this. 

I'm pretty sure this sort of thing has been done as part of precision landing - where I believe they used velocity mode control. I recommend you raise this question on the gitter channel: gitter.im/dronekit/dronekit-python to see if there is a good project you can work with. This isn't much different from the red-baloon project which Randy Mackay did.

**Comment by hamishwillee** [comment]
I'm closing this because we can't expose Solo internals if 3DR do not wish us to!
