### ISSUE TITLE
how to switch controls between 2 vehicles using mission planner

### ISSUE THREAD

**Issue by awesomeawj** [dronekit/dronekit-python#628]
hi guys, im currently doing a project on surveillance drone + rover. so basically we're using pixhawk for both the drone and rover. how do i switch the controls between the 2 vehicles? thanks!
sorry for the bad english

**Comment by hamishwillee** [comment]
Hi @awesomeawj 

Please raise this on the [discussion boards here](https://discuss.dronekit.io/c/python) as this isn't so much an issue with the system as a "how do I go about looking into this sort of problem" discussion.

When you raise the question please explain the architecture in more detail. Specifically I THINK you are saying that you are writing a ground station that can talk to a rover OR a drone. You want to be able to address some commands to the drone and some to the rover ... Is that correct? What network are the commands being sent over (telemetry links, wifi?). Or is there some other architecture?

I am closing this now as "not the best place to ask this question".
