### ISSUE TITLE
Is there a way to control yaw and velocity in one message?

### ISSUE THREAD

**Issue by alexblack** [dronekit/dronekit-python#630]
Currently I'm sending separate `set_position_target_local_ned` and `MAV_CMD_CONDITION_YAW` commands every time, is there a way to one command to tell the drone both velocity and yaw?

**Comment by squilter** [comment]
According to the mavlink spec, it should be possible to send the yaw in the `set_position_target_local_ned` message, but this is not currently supported on the [ArduCopter side](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/GCS_Mavlink.cpp#L1700). You'll have to send two.
