### ISSUE TITLE
exception.attributeerror 'nonetype' object has no attribute 'error' 

### ISSUE THREAD

**Issue by keyurrakholiya** [dronekit/dronekit-python#636]
i am using R-pi
using dronekit 2.4.0
example : vehicle_state.py

getting error:
![screenshot 215](https://cloud.githubusercontent.com/assets/12994106/15984157/bfec88f2-2fde-11e6-95a7-350853daf723.png)

**Comment by hamishwillee** [comment]
Looks like a bug. @peterbarker suggestions for debugging? 

@keyurrakholiya Can you run Python 2.7? This isn't likely the problem, but it is one less dependency to worry about.

**Comment by keyurrakholiya** [comment]
@hamishwillee 
yes i am using python 2.7

**Comment by peterbarker** [comment]
This is a race condition in shutdown.  It can safely be ignored - but a patch to close down the mavlink threads nicely would be better!

**Comment by peterbarker** [comment]
This issue should have been fixed by #648
