### ISSUE TITLE
RC overrides causes vehicle disarmed when RC is off

### ISSUE THREAD

**Issue by FlyingCatAlex** [dronekit/dronekit-python#651]
I need to use RC overrides to send interruption command in autonomous collision avoidance flight. When RC is turned on, I can set the desired throttle value using vehicle.channels.overrides['3'] = someValue. But when RC is off, when I send a new value to vehicle.channels.overrides['3'], the vehicle disarmed immediately.  The new value is set successfully. 

I may not need RC in my project. Because I want the drone to complete a mission and avoid collision automatically without any human interference. Is there any way to get rid of RC ?

**Comment by hamishwillee** [comment]
This will be autopilot behaviour (not specifically Dronekit). I therefore suggest you ask the question on the [discussion boards](http://discuss.ardupilot.org/).

You will have to define what you mean by "get rid of RC". If it is possible, it will be a [parameter change](http://ardupilot.org/copter/docs/parameters.html).

I am closing this as "out of scope".
