### ISSUE TITLE
requirements.txt has pymavlink pinned to 2.0.6 instead of 2.0.8

### ISSUE THREAD

**Issue by cclauss** [dronekit/dronekit-python#674]
pymavlink 2.0.8 opens up the door to working on Python3.

This is part of PR https://github.com/dronekit/dronekit-python/pull/673 but could also be done separately.

**Comment by markrjr** [comment]
At this time of writing, it should be updated to 2.1.0 in order to include support for the new copter mode GUIDED_NOGPS.

**Comment by cclauss** [comment]
https://github.com/dronekit/dronekit-python/blob/master/requirements.txt#L1
