### ISSUE TITLE
Implementation of Gazebo in ROS with DroneKit-SITL 

### ISSUE THREAD

**Issue by munkarkin96** [dronekit/dronekit-python#686]
DroneKit provides such a modular and powerful platform for building of UAVs. With DroneKit-SITL, 2D simulation can help developers to clearly visualise the behaviour of the vehicle, and will tend to succeed with extensive error checking in the script. 

However, the problem arises with the vehicle flying indoor. A 2 dimensional simulation is no longer sufficient, and the application demands for more extensive simulation in 3D using Gazebo, for instance. 

It will be relatively useful to be able to CAD a virtual environment for indoor flying, which will be very useful for applications such as: 

1. Navigating in a tunnel with constant wind disturbances 
2. Flying indoor for SLAM 
3. Obstacle Avoidance 
4. Visualisation of computer vision related work 

and the list goes on and on. 

Does the team behind this open-sourced platform has any intention of implementing the Gazebo simulator? O

**Comment by squilter** [comment]
Yep, there's a bit of setup required, but try this:
http://ardupilot.org/dev/docs/using-gazebo-simulator-with-sitl.html
