### ISSUE TITLE
Channel Override Alternative

### ISSUE THREAD

**Issue by jodumagpi** [dronekit/dronekit-python#689]
I have been using channel override to specify the approximate direction of the drone (angle rotation) and control the speed as it moves forward. This is so that the drone can land precisely on a target based on it's approximate horizontal and vertical distance. However, I've read on the documentation that this is "highly dis-commended". If so, what are the alternative commands?

**Comment by peterbarker** [comment]
On Mon, 26 Dec 2016, Jo Dumagpi wrote:

> I have been using channel override to specify the approximate direction of
> the drone (angle rotation) and control the speed as it moves forward. This
> is so that the drone can land precisely on a target based on it's
> approximate horizontal and vertical distance. However, I've read on the
> documentation that this is "highly dis-commended". If so, what are the
> alternative commands?

guided mode, specifying angles at which the aircraft should be oriented.

**Comment by cheintz** [comment]
Is there a similar function for fixed wing? Preferably one that behaves similarly to FBWB? It seems guided mode for fixed wing sets target roll and pitch angles, rather than any direct transnational velocities.

**Comment by studroid** [comment]
You may refer to this: #712 
Changing attribute is more likely what you are looking for.
