### ISSUE TITLE
Add CommandSequence.takeoff to the public API

### ISSUE THREAD

**Issue by hamishwillee** [dronekit/dronekit-python#70]
This is defined in the implementation class (not the interface class) and does not appear in the documentation. 

It needs to be made visible in the documentation, ideally by defining it in the interface.

Note: I split this out from #64 so I can assign ownership to @mrpollo .

**Comment by hamishwillee** [comment]
#134 adds the method to the documentation as part of the "class docs". I'm leaving this open because even though this will fix the documentation it doesn't do it in the right way - which is to add the method into the __init__.py .

**Comment by tcr3dr** [comment]
@hamishwillee Is this technically a bug still? Looks like it's part of CommandSequence now (although we may move that into Vehicle proper?)

**Comment by hamishwillee** [comment]
@tcr3dr No, this can be closed. 

I will move the documentation for all methods under the methods themselves (out of the "class level" docs) as soon as we get some API stability.

**Comment by tcr3dr** [comment]
@hamishwillee Sounds great.
