### ISSUE TITLE
How to control drone through datalink

### ISSUE THREAD

**Issue by adiredz** [dronekit/dronekit-python#722]
Hello guys, im trying to control my drone through data. Not using RC at all, or i am using a PS3 controller and need to control the roll, yaw, pitch and throttle through dronekit. Cant seem to get this working!

**Comment by hamishwillee** [comment]
Best place to ask this might be gitter: https://gitter.im/dronekit/dronekit-python
You should expand on what you have tried, what vehicle etc etc.
