### ISSUE TITLE
Remove the commented out "Test custom commands" from examples

### ISSUE THREAD

**Issue by hamishwillee** [dronekit/dronekit-python#73]
Remove unnecessary code from examples to make them clean and clear (including the commented out code like "Test custom commands".
https://github.com/diydrones/dronekit-python/blob/master/example/small_demo/small_demo.py#L47

We should have a separate guide and reference on custom commands that uses this.

Note, no need to remove from [perf_test.py](https://github.com/diydrones/dronekit-python/blob/master/example/perf/perf_test.py#L232) as this is test rather than example code

**Comment by hamishwillee** [comment]
#124 fixes the small_demo case.

**Comment by tcr3dr** [comment]
Closed!
