### ISSUE TITLE
Serial port is dead

### ISSUE THREAD

**Issue by BdT141** [dronekit/dronekit-python#735]
Hello,

I'm trying to communicate between RPi Zero and Pixhawk 4 over the Pi's uart, but I get the error message "The device /dev/ttyS0 is dead" or /dev/serial0. I've tried looking in the souce code which function is giving that error, but can't find it. The serial port isn't the problem because I've tested it with other devices and it works. I was wondering if the problem is on the Pi's side or the Pixhawk's side.

Thank,
Brandon

**Comment by BdT141** [comment]
Problem was I was trying to use Python3.

**Comment by peterbarker** [comment]
On Mon, 17 Jul 2017, Brandon du Toit wrote:

> Problem was I was trying to use Python3.

Thanks for the update.  We'll now know more next time we see the same 
symptoms!

**Comment by GTSyu** [comment]
> Problem was I was trying to use Python3.

Exceuse me. So could you please share how did you solve the problem?? did you reinstall mavlink and the dronekit in python2 version?
