### ISSUE TITLE
Mavlink Command not recognized

### ISSUE THREAD

**Issue by Ilyasem** [dronekit/dronekit-python#745]
Hello,

I am getting this error:
AttributeError: 'module' object has no attribute 'MAV_DO_REPEAT_SERVO'

I was unable to find any information already online, I am running DroneKit 2.9.0 on a Rpi3 + Navio2 shield
running ArduCopter 3.4.6

My goal is to send ~1500 (1490) PWM to Servos 9-12 (Motors) because they are reversible and arm by receiving neutral throttle for 1 second.

My code:
```python
from dronekit import connect
import time
import dronekit
import socket
import exceptions
from pymavlink import mavutil, mavwp
import pymavlink

# Connect to the Vehicle (in this case a tcp endpoint)
vehicle = connect('tcp:127.0.0.1:14552', wait_ready=True)

print "Basic pre-arm checks"
# Don't try to arm until autopilot is ready
#while not vehicle.is_armable:
#    print " Waiting for vehicle to initialise..."
#    time.sleep(1)

print "Arming motors"
# Copter should arm in GUIDED mode
#vehicle.mode    = dronekit.VehicleMode("GUIDED_NOGPS")

msg1 = vehicle.message_factory.command_long_encode(
    0, 0,    # target system, target component
    mavutil.mavlink.MAV_CMD_DO_SET_MODE, #command
    0, #confirmation
    20,
    0, 0, 0, 0, 0, 0 )
# send command to vehicle
vehicle.send_mavlink(msg1)

vehicle.armed   = True

# Confirm vehicle armed before attempting to take off
while not vehicle.armed:
    print " Waiting for arming..."
    time.sleep(1)

pins= [9,10,11,12]
msg=[]
for x in pins:
    temp = vehicle.message_factory.command_long_encode(
        0, 0,    # target_system, target_component
        mavutil.mavlink.MAV_DO_REPEAT_SERVO, #command
        0, #confirmation
        x ,    # param 1, servo No
        1490,          # param 2, pwm
        1,          # param 3, repeat #
        2, # param 4, delay
        0, 0, 0)    # param 5 ~ 7 not used
    msg.append(temp)
    
# send command to vehicle
for i in msg:
    vehicle.send_mavlink(i)

```
Here is the command in question:
http://ardupilot.org/copter/docs/common-mavlink-mission-command-messages-mav_cmd.html#mav-cmd-do-repeat-servo

Additionally, I am attempting to set the mode to GUIDED_NOGPS as I am indoors and need to arm, but am only able to do this via Mission Planner. While I found this workaround any help on setting the appropriate mode in DroneKit would be appreciated as well.

**Comment by peterbarker** [comment]
On Fri, 11 Aug 2017, Ilyasem wrote:

> I am getting this error:
> AttributeError: 'module' object has no attribute 'MAV_DO_REPEAT_SERVO'

ITYM `MAV_CMD_DO_REPEAT_SERVO`
