### ISSUE TITLE
Issue with vehicle.commands, we cannot access last element using cmds[-1]

### ISSUE THREAD

**Issue by ArkadiuszNiemiec** [dronekit/dronekit-python#746]
Beacuse of changes in the CommandSequence class, especially in the line [2791](https://github.com/dronekit/dronekit-python/blob/92ee230792f7f3005556e2ad772d12bbd43f6684/dronekit/__init__.py#L2791) of the `__init__.py` file, we cannot access commands using negative indexes like [-1] for last element (it adds +1, which makes it 0). I am pretty sure that around one year ago it was working fine.

Here's a snippet of my old code:
```
        cmds = vehicle.commands
        cmds.download()
        cmds.wait_ready() # wait until download is complete.

        if cmds[-1].command != mavutil.mavlink.MAV_CMD_NAV_LOITER_UNLIM:
```

I think CommandSequence should support negative addressing or at least correct ["Operations include ‘array style’ indexed access to the various contained waypoints."](http://python.dronekit.io/automodule.html) line it the docs :)

**Comment by hamishwillee** [comment]
Well over a year ago the cmds were set so you couldn't over or underrun. This was to remove the zero'th hidden home position waypoint from the array - which was confusing to users.  The behaviour may change at some point to better support PX4 - which doesn't have the zero position home waypoint. 
@peterbarker  Anything to add?
