### ISSUE TITLE
Running the scripts thru Mavproxy

### ISSUE THREAD

**Issue by vincentwen1995** [dronekit/dronekit-python#787]
Hi, I have a question about the compatibility of dronekit-python 2.0 with Mavproxy.
In our project, the pixhawk flight controller is used with a odroid-c2 companion computer. The connection between the pixhawk and the odroid is set up thru serial and between the ground station(PC) and the odroid is set up thru telemetry. The overall connection interface we are using is Mavproxy. 
So while the drone is in the air, we don't have access to the shell of the odroid, and, therefore, could not simply run the python script in the linux terminal. 
Hence, I was wondering whether there is way to start the dronekit-python api and run a specific script located on the odroid in the Mavproxy interface? As I read, this was possible in the older version (1.5), but in the update to 2.0, the dependency on Mavproxy was relaxed.

**Comment by peterbarker** [comment]
On Sat, 20 Jan 2018, vincentwen1995 wrote:

> Hence, I was wondering whether there is way to start the dronekit-python api and run a specific script located on the odroid in the Mavproxy interface? As
> I read, this was possible in the older version (1.5), but in the update to 2.0, the dependency on Mavproxy was relaxed.

Have your dronekit-python script always running.

Monitor an RC input channel to change the script's behaviour.

I've previously done this to start/stop video recording, for example.
