### ISSUE TITLE
mavproxy.py command not found 

### ISSUE THREAD

**Issue by duckhang9113** [dronekit/dronekit-python#797]
I'm running ubuntu 17. and install MAVProxy according to the instruction from https://ardupilot.github.io/MAVProxy/html/getting_started/download_and_installation.html. 
I'm not sure what this mean so I skip this step:
If not already set, MAVProxy needs to be on the system path:

echo "export PATH=$PATH:$HOME/.local/bin" >> ~/.bashrc

I try to run mavproxy.py. It returns command not found. Please help me!

**Comment by pietrodn** [comment]
Did you reload `.bashrc` in the shell?
You can close and re-open the terminal, or do: `source ~/.bashrc`

**Comment by hamishwillee** [comment]
> Also, this is a duplicate of #778.

Yes it is. @duckhang9113 , please continue discussion on #778.

Thanks @pietrodn

**Comment by duckhang9113** [comment]
@pietrodn I closed the terminal and re-open it. it's solved. Thank you for your help 🥇 👍 :)
