### ISSUE TITLE
MAV_CMD_DO_SET_SERVO using dronekit

### ISSUE THREAD

**Issue by dinesh286** [dronekit/dronekit-python#804]
I have to use MAV_CMD_DO_SET_SERVO mavlink command in dronekit python for controlling a fixed wing UAV.  Is there any syntax available.  I tried channeloverride and its working. since i want to put my own autopilot in a companion computer and many advised not to use channeloverride i want to use MAV_CMD_DO_SET_SERVO.

**Comment by hamishwillee** [comment]
If you're going to use DK-Python then you'll have to use the channel override - I'm pretty sure we don't provide any other mechanism for direct servo control.

Not sure what you mean by  "i want to put my own autopilot in a companion computer". That is something you should discuss in the gitter channel - depending on what you want to do this probably not a good use case for DroneKit.
