### ISSUE TITLE
How to connect dronekit with real vehicle?

### ISSUE THREAD

**Issue by MathiasDePaepe** [dronekit/dronekit-python#824]
I want to execute the example codes on a real vehicle, how can I do this in dronekit? The connection string is now a SITL simulation with string 'tcp:127.0.0.1:5760'. I tried to change the connection string to the IP address of the drone who has connected to my PC over ssh connection, but i didn't seem to work that way.

How to solve this problem?

**Comment by peterbarker** [comment]
On Wed, 2 May 2018, Mathias De Paepe wrote:

> I want to execute the example codes on a real vehicle, how can I do this in
> dronekit? The connection string is now a SITL simulation with string
> 'tcp:127.0.0.1:5760'. I tried to change the connection string to the IP
> address of the drone who has connected to my PC over ssh connection, but i
> didn't seem to work that way.

Often "--connect :14550" to listen for UDP broadcast messages.

If it's a radio modem then --connect /dev/serial/by-id/... (on linux). 
Something to do with COM?? under Windows....
