### ISSUE TITLE
How to Code the Vtol Mavlink commands

### ISSUE THREAD

**Issue by jasonscupham** [dronekit/dronekit-python#846]
Hi everyone, 
I have just looked at this website for all the commands that Mavlink can perform: https://mavlink.io/en/messages/common.html#MAV_TYPE_VTOL_RESERVED2

I saw some of the VTOL commands there as i'm looking to do something similar but i'm new to coding. I was how these commands would be written in python.

Also I using mission planner which has some waypoints that can be set to VTOL takeoff, land and transition. I was wondering how I could read when the VTOL aircraft is coming to that waypoint, detect it and activate a def function for that transition.

Cheers Jason

**Comment by hamishwillee** [comment]
Duplicate of https://github.com/dronekit/dronekit-python/issues/847
