### ISSUE TITLE
Cannot connect to the vehicle via telemetry 

### ISSUE THREAD

**Issue by Rainerino** [dronekit/dronekit-python#850]
I cannot connect to pixhawk 2.4.8 through telemetry. 
Using: 
Ubuntu 16.04 LTS, 
dronekit 2.9.1
pymavlink 2.2.10
pyserial 3.4
python 3.5.2

Hardware: I am using a 915MHz telemetry and have tested it in Mission planner and QGroundControl with the exact same set up, have done multiple auto mission with it and haven't gotten any problems. 

I have tried: 
`v= dronekit.connect("/dev/ttyUSB0", baud=57600, wait_ready=True)`
`v= dronekit.connect("/dev/ttyUSB0", baud=57600, rate=10, wait_ready=True)`

`v = dronekit.connect("/dev/ttyUSB0", baud=57600, wait_ready=False)` with
`v.wait_ready(True, timeout=30)` and even 60, 180 and 240

`vehicle = connect("/dev/ttyUSB0", baud=57600, wait_ready=False, heartbeat_timeout=15)`
`vehicle.wait_ready('autopilot_version', timeout=180)`

Output:
with `v= dronekit.connect("/dev/ttyUSB0", baud=57600`, it connects and then gets disconnected right away:
![image](https://user-images.githubusercontent.com/18321830/44896010-9391ef80-acab-11e8-8bc4-2a2eb50adfad.png)
I used ipython there, but I have tried it in terminal and python script.
 Increase timeout will just timeout after a long time. 

I used QGroundContorl with system ID 255 and it connects with no problem. When I test I have made sure that 
- The port exist
- Nothing else is using it
- No Ground Control Software is open

With the same setup successfully using dronekit connecting with:
- Wired connection to pixhawk 
- `vehicle = connect("/dev/ttyACM0", baud=115200, wait_ready=True)`
- Telemetry 2 connection to pixhawk
- `vehicle = dronekit.connect("/dev/ttyUSB0", wait_ready=True, baud=1500000)`
- Any Simulators (sim_vehicle, dronekit, gazebo and Javsim)

Thank you for helping! 
EDIT 1: I downgraded pymavlink to 2.0.6, still cannot connect
![image](https://user-images.githubusercontent.com/18321830/44901608-b8db2980-acbc-11e8-8f64-643bde446f9d.png)

**Comment by Rainerino** [comment]
Do dreonkit development team ignore any problems in python 3 platform because it's not officially supported?

**Comment by hamishwillee** [comment]
The team will take PRs for fixes in Python 3, but if you just raise an issue, then the chances of it being fixed in any sort of timely manner are low.

**Comment by Rainerino** [comment]
Thank you @hamishwillee for the reply! I am not in a hurry, just want to fix this if possible.

**Comment by hamishwillee** [comment]
@Rainerino Perhaps I should say "probably not fixed until someone creates a PR". All of the Python 3 work was done by community, and indeed most of the work over the last few years. There is some work done by the various projects that use this software, but not a great deal.

**Comment by Guohao91** [comment]
@Rainerino Hi, Yan yiyi? We have a extremely similar problem, as like connecting Pixhawk 4 with Companion computer via TELEM2 or micro USB Port.
