### ISSUE TITLE
How to MUTE connection logs?

### ISSUE THREAD

**Issue by mustaphos** [dronekit/dronekit-python#862]
Hi.
Is there a way to mute console log outputs?
Thanks for answers.

**Comment by pietrodn** [comment]
You could monkey-patch the methods in `dronekit/util.py`:

```python
from dronekit import util
util.errprinter = lambda msg: None
util.logger = lambda msg: None
```

Caveat: do this before importing the DroneKit module.

**Comment by pietrodn** [comment]
Now dronekit uses the built-in Python `logging` module. Now you can do:

```python
import logging
logging.getLogger('dronekit').addHandler(logging.NullHandler())
logging.getLogger('autopilot').addHandler(logging.NullHandler())
```

Where the `autopilot` logger handles the log messages coming from the firmware, while the `dronekit` logger handles the messages coming from the library.

I think this issue can be closed now.

**Comment by mustaphos** [comment]
@pietrodn thanks for your support.
