### ISSUE TITLE
Using SET_ATTITUDE_TARGET in Guided or Pos_Hold mode

### ISSUE THREAD

**Issue by JorgeG30** [dronekit/dronekit-python#882]
Hello, 

I was wondering if it is possible to use the SET_ATTITUDE_TARGET while in Guided or Pos_hold mode. I used it in the Guided_NOGPS mode and it worked but not the way I expected. I was expecting for the drone to take off, hold its current position, and then move backward and forward due to the command in the example. But it ended up taking off and not holding its position. It did perform the commands but it didn't do what I originally expected. Is it possible to use the same command while using any of the other modes. Thank you

**Comment by hamishwillee** [comment]
THis is not a bug and it isn't really about DroneKit - it is ardupilot specific. So you should ask it in the ArduPilot forums. 

That said, an out of date list of supported commands in guided mode says this should work in guided mode: http://ardupilot.org/dev/docs/copter-commands-in-guided-mode.html?highlight=set_attitude_target#movement-commands

It probably doesn't work in other modes. YOu might have to check the source.
