### ISSUE TITLE
Dronekit supported drone Recommendation

### ISSUE THREAD

**Issue by MuhammadFaizanKhan** [dronekit/dronekit-python#886]
I am willing to test drone kit custom application, can anyone recommend me the state of the art drone (low cost) that fully support drone kit?

**Comment by hamishwillee** [comment]
Any drone running ArduPilot will be "particularly compatible". Suggest you ask for recommendations on ArduPilot forums. You will need to specify if DroneKit is to run on a ground station or on a companion computer, as it will change the recommendation.
