### ISSUE TITLE
Re-enable AppVeyor CI

### ISSUE THREAD

**Issue by pietrodn** [dronekit/dronekit-python#893]
After the fixes in #878, the AppVeyor configuration for CI is good to go.
However AppVeyor is not enabled for the repo.

I think it would be a good idea to enable it in order to have Windows testing too. :-)

**Comment by peterbarker** [comment]
On Sat, 29 Dec 2018, Pietro De Nicolao wrote:

> After the fixes in #878, the AppVeyor configuration for CI is good to go.
> However AppVeyor is not enabled for the repo.

Well.. I changed the webhook to "active".  Let me know how it works out 
:-)

**Comment by pietrodn** [comment]
Uhm, can you also force it to make a build of the current master? :-)

**Comment by peterbarker** [comment]
On Sun, 30 Dec 2018, Pietro De Nicolao wrote:

> Uhm, can you also force it to make a build of the current master? :-)

Nope.  You'll have to get a nice PR together :-P

**Comment by pietrodn** [comment]
The latest commit built successfully, so this issue is solved!
