### ISSUE TITLE
direct access to Drone live video

### ISSUE THREAD

**Issue by m3m3-chan** [dronekit/dronekit-python#895]
Hello! 
I am planning to use a drone to run some python computer vision/image processing. I would like to know if there's a direct way to access the live video feed from the drone using Dronekit?

**Comment by hamishwillee** [comment]
No. Dronekit is a MAVLInk API and there is no mavlink protocol for getting video stream information. 

Systems typically have cameras and processing integrated together on a companion computer. The [Dronecode Camera Manager](https://camera-manager.dronecode.org/en/) sets up RTSP streams, but that is outside of its MAVLink API.
