### ISSUE TITLE
Setting EKF origin. MAV_CMD_DO_SET_HOME doesn't work.

### ISSUE THREAD

**Issue by dollop80** [dronekit/dronekit-python#903]
A quad runs ArduCopter 3.7 (checked also a SITL ArduCopter 3.3).
To be able to navigate in NO_GPS environment it is vital for ArduCopter to set home position. It can be done via MissionPlanner: Right click -> set home here.
But sending the command from companion computer or whatever via dronekit returns the line

`Got MAVLink msg: COMMAND_ACK {command : 179, result : 4}
`
I try to do it like this
```
def set_home(self, aLocation, aCurrent=1):
   msg = self.vehicle.message_factory.command_long_encode(
      0, 0,  # target system, target component
      mavutil.mavlink.MAV_CMD_DO_SET_HOME,  # command
      0,  # confirmation
      aCurrent,  # param 1: 1 to use current position, 2 to use the entered values.
      0, 0, 0,  # params 2-4
      aLocation.lat,
      aLocation.lon,
      aLocation.alt
      )
      # send command to vehicle
      self.vehicle.send_mavlink(msg)
      self.vehicle.flush()
```
aLocation values are not zeros.

The only difference between the Mission Planner Message and the dronekit-python message is the component ID, which is 0xbe for MP and 0x00 with dronekit.

So I tried to initialize a vehicle object like this:

`self.vehicle = connect('com102', wait_ready=True, source_system=190)
`
But it doesn't help

See the problem reports also here https://discuss.ardupilot.org/t/setting-ekf-origin-through-mavlink/17713

Thanx

**Comment by peterbarker** [comment]
On Thu, 31 Jan 2019, Constantine Safronov wrote:

> A quad runs ArduCopter 3.7 (checked also a SITL ArduCopter 3.3).
> To be able to navigate in NO_GPS environment it is vital for ArduCopter to set home position. It can be done via MissionPlanner: Right click -> set home
> here.

Is MissionPlanner implicitly setting the EKF origin?

**Comment by amilcarlucas** [comment]
There have been some recent changes to this. Can you retest master?

**Comment by peterbarker** [comment]
@dollop80 Did you get this sorted?  Please re-open if not.

**Comment by shubham9436** [comment]
Even I am facing the same issue
