### ISSUE TITLE
yaw change in APM:Copter V3.4-dev

### ISSUE THREAD

**Issue by shubham9436** [dronekit/dronekit-python#914]
Hi team,

How do I control the yaw of the drone?
I am using APM:Copter V3.4-dev .
I have used https://github.com/dronekit/dronekit-python/blob/master/examples/set_attitude_target/set_attitude_target.py . But set_attitude(yaw_rate = 30, thrust = 0.5, duration = 3) does not work properly.

I need to rotate the drone on its yaw axis. I am using Gazebo simulator

**Comment by pietrodn** [comment]
If you only need to control the yaw, you could use the [`SET_POSITION_TARGET_LOCAL_NED`](https://mavlink.io/en/messages/common.html#SET_POSITION_TARGET_LOCAL_NED) message, setting the `type_mask` to ignore all the axes except the yaw.
