### ISSUE TITLE
how to use Dronekit python with python3 when i am trying run with python 3 i got a error

### ISSUE THREAD

**Issue by nagendra092918** [dronekit/dronekit-python#921]
![image](https://user-images.githubusercontent.com/29352982/54763702-73605880-4c1c-11e9-961c-c741e04f2994.png)
![Capture](https://user-images.githubusercontent.com/29352982/54763761-91c65400-4c1c-11e9-9d3c-64c4fe1f9a73.PNG)

**Comment by AdamHtooLwin** [comment]
Did you install to python or python3? Besides, dronekit isn't supported on Python 3 I believe.

**Comment by nagendra092918** [comment]
i installed python and python3.here python2 working fine on dronekit but python3 not working
but in pip install they given supported for python3 please check once image also if have any idea please tell to me . i tried alot
![dronekit_problem](https://user-images.githubusercontent.com/29352982/56342324-5300cb00-61d5-11e9-8646-3a421c876c05.PNG)

**Comment by wrmichaelmak** [comment]
Are you able to solve this problem?

**Comment by leonardocfor** [comment]
Nagendra, why are you using sudo to run the simple_goto script? Try running it without sudo. It should work. Otherwise can you show the source code of the script please?
