### ISSUE TITLE
Raspberry pi ArduCopter V3.2.1 arming issue

### ISSUE THREAD

**Issue by oguzkaganaltas** [dronekit/dronekit-python#926]
I am trying to run brushless motors via script on raspberry pi, using arducopter. with this code. and i am having this output 
CRITICAL:autopilot:ArduCopter V3.2.1 (36b405fb)
CRITICAL:autopilot:Frame: QUAD
ERROR:autopilot:PreArm: Need 3D Fix
Basic Prearm checks..dont touch!!
Waiting for vehicle to initialize
Arming Motors..
Is Armed:False
Waiting for arming...Mode:VehicleMode:POSHOLD
Is Armed:False
Waiting for arming...Mode:VehicleMode:POSHOLD
Is Armed:False
Waiting for arming...Mode:VehicleMode:POSHOLD
Is Armed:False
Waiting for arming...Mode:VehicleMode:POSHOLD
Is Armed:False
...
...
I connected ardupilot to raspberry pi through serial port.

```
from dronekit import connect,VehicleMode,LocationGlobalRelative
from pymavlink import mavutil
import time

connection_string = "/dev/ttyS0"
vehicle = connect(connection_string, baud= 57600, wait_ready=True)


def arm_and_takeoff(aTargetAlt):
	print("Basic Prearm checks..dont touch!!")
	print("Waiting for vehicle to initialize")
	time.sleep(1)
	print("Arming Motors..")
	
	vehicle.mode = VehicleMode("STABILIZE")

	vehicle.armed = True
	vehicle.flush()
        print("Is Armed:% s"% vehicle.armed)
	
	while not vehicle.armed:
		print("Waiting for arming...Mode:% s"% vehicle.mode)
		print("Is Armed:% s"% vehicle.armed)
		vehicle.armed = True
		time.sleep(2)
		
	print("Taking Off..")
	vehicle.simple_takeOff(aTargetAlt)

	while True:
		print("Altitude: ",vehicle.location.global_relative_frame.alt)
		#Break and return from function just below target altitude.
		if vehicle.location.global_relative_frame.alt>=aTargetAlt: 
			print("Reached Target Altitude..")
			break
		time.sleep(2)
	
vehicle.close()
arm_and_takeoff(50)```

**Comment by mustafa-gokce** [comment]
It is really a strange behavior.
Did you try to upload the latest firmware (or reinstall) to pixhawk?
Also why your drone starts in POSHOLD mode?
And also `vehicle.close()` must be inside the function.
You trying to reach the closed vehicle when you run `arm_and_takeoff()` in the last row.
