### ISSUE TITLE
Dronekit Python Documentation

### ISSUE THREAD

**Issue by bozkurthan** [dronekit/dronekit-python#944]
Hello, I was following "Dronekit.io" document page which is guide for python. 3 or 4 weeks ago, I couldn't open guide page. http://python.dronekit.io/guide/index.html 

Did the guide page is transported? I can't find any information about this.

![Screenshot from 2019-05-28 11-06-08](https://user-images.githubusercontent.com/44507545/58461574-aa7d4980-8138-11e9-8d88-f0099bc7506d.png)

Thank you.

**Comment by hamishwillee** [comment]
Duplicate #932 
These also got mirrored. We're waiting on republishing to happen.

**Comment by bozkurthan** [comment]
I'm really sorry. I couldn't find this issue. I'm closing issue.

Thank you hamishwillee.
