### ISSUE TITLE
Documentation links of dronekit.io are broken

### ISSUE THREAD

**Issue by maroquio** [dronekit/dronekit-python#953]
Hello.
I'm trying to access the documentation of DroneKit Python from the official website and it is not working anymore. Is this a server problem or was it migrated to another place?

**Comment by hamishwillee** [comment]
True. Closing, this is a duplicate. 

But, I have fixed up all the links on the readme so they now point to new docs on readthedocs: https://github.com/dronekit/dronekit-python/blob/master/README.md
