### ISSUE TITLE
Automatic Landing when Program Ends

### ISSUE THREAD

**Issue by shubham9436** [dronekit/dronekit-python#974]
I am using arm_and_takeoff(5) function. After that the program ends.
The vehicle mode gets automatically changed to LAND mode.
Is this a expected behavior?

I am using Gazebo for simulation.

**Comment by hamishwillee** [comment]
Probably not, but you'd have to do a whole lot more information for anyone to help you. Ie how did you install dronekit, what flight stack and flight stack version you are using. What exactly you saw - ie did it take off? What code were you running?

Depending on what you want to do you might add some of the additional telemetry in https://dronekit-python.readthedocs.io/en/latest/guide/taking_off.html so you can see how far the vehicle got and what its state was before it decided to land.
