### ISSUE TITLE
ERROR MissionPlanner.Utilities.Firmware

### ISSUE THREAD

**Issue by gelson12** [dronekit/dronekit-python#976]
Greetings,

could someone assist me with the folllwoing error:

ERROR MissionPlanner.Utilities.Firmware - System.Net.WebException: The remote server returned an error: (404) Not Found.
  at System.Net.HttpWebRequest.GetResponseFromData (System.Net.WebResponseStream stream, System.Threading.CancellationToken cancellationToken) [0x0017e] in <a9a08e39ba304bd0a84c49bd158dfc02>:0 

I took the liberty of attaching the entire log file:

[MissionPlanner SITL firmware download log.txt](https://github.com/dronekit/dronekit-python/files/3691289/MissionPlanner.SITL.firmware.download.log.txt)

**Comment by peterbarker** [comment]
I can't see why this issue has been raised against dronekit-python; the phrase "dronekit" doesn't appear in that log you pasted.

Please reopen the issue if you think I've closed it in error.
