### ISSUE TITLE
Can't connect dronekit scripts to my solo copter(Pixhawk4 controller), although the example scripts work all fine with SITL instance 

### ISSUE THREAD

**Issue by Guohao91** [dronekit/dronekit-python#996]
when I try to run any one example script onto my UAV(Pixhawk4 controller), it doesn't work well, problem shown as:
![image](https://user-images.githubusercontent.com/54188732/71116785-beef6500-21a2-11ea-8d35-835af1566866.png)
All the examples work fine with SITL instance, as well as onto my Mavproxy.
So i am quite confused why my UAV can connect mavproxy while not the example scripts.
and I am pretty sure my port "/dev/ttyACM0" is correct.

**Comment by mohamadsaab** [comment]
hi , did you find a solution ? I'm facing the same problem

**Comment by Guohao91** [comment]
@mohamadsaab hi! sorry for so late reply. 
so i don't remember what reason it was exactly, but i am sure the problem should came out of two possible scenarios:
no.1:in the flight controller side, you need to choose either micro usb port or TELEM2 port, i am using micro usb port to connect this time while I heard some companion computers don't work with TELEM2 port. so when i use TELEM2 port to connect with, flight controller always fails to connect my script.
no.2:   in the NUC(companion computer) side, there are usually 3 or 4 usb ports on the computer right? so I probably made a mistake to connect a port with identifying a wrong port name, like the port i was connecting is ACM1, but i typed : /dev/ttyACM0. so it failed to callback my script.
Hope above explanations can help you even a bit.

**Comment by mohamadsaab** [comment]
Ok I understand . I am using navio2 which is HAT for raspberry pi so i can't change the port unfortunately . I thought it would be another reason but thank you for replying.
